# Generated by Django 5.2.5 on 2026-08-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Display on the homepage.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which keywords are shown.')),
            ],
            options={
                'ordering': ['display_order', 'keyword'],
            },
        ),
    ]
