# Generated by Django 5.2.5 on 2026-08-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seokeyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOKeyword',
        ),
    ]
