# Generated by Django 6.1 on 2026-08-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Official response sent back to the user.'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read_by_user',
            field=models.BooleanField(default=False, help_text='Whether the user has viewed the response.'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the team replied.', null=True),
        ),
    ]
