# Generated by Django 6.1 on 2026-09-15 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_category_id_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True),
        ),
    ]
