# Generated by Django 5.2.5 on 2026-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text message'), ('OFFER', 'Offer')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='offer_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
