# Generated by Django 5.2.5 on 2026-08-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_attachment_message_attachment_name'),
        ('services', '0003_alter_category_id_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offer_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_messages', to='services.service'),
        ),
    ]
