# Generated by Django 6.0.7 on 2026-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='headline',
            field=models.CharField(blank=True, help_text="e.g. 'Senior Data Engineer'", max_length=150),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated, e.g. Python, SQL, Power BI, dbt', max_length=400),
        ),
    ]
