# Generated by Django 5.1.15 on 2026-08-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_specialistprofile_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by a manager to operate on the platform'),
        ),
    ]
