# Generated by Django 5.1.15 on 2026-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialistprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='default_payment_method',
            field=models.CharField(blank=True, help_text='e.g. CARD, BALANCE, PAYPAL', max_length=30),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='payout_details',
            field=models.TextField(blank=True, help_text='JSON or human-readable payout details (account, email, etc.)'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe (recommended)'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer')], max_length=20),
        ),
    ]
