# Generated by Django 5.1.15 on 2026-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
