# Generated by Django 5.2.5 on 2026-08-08 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deposittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
