# Generated by Django 5.2.5 on 2026-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_referral_code_user_referred_by_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='default_payment_method',
            field=models.CharField(blank=True, help_text='e.g. CARD, MPESA, BALANCE, PAYPAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe (recommended)'), ('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('BANK', 'Bank transfer')], max_length=20),
        ),
    ]
