# Generated by Django 6.1 on 2026-09-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_specialisttestattempt_responses'),
        ('accounts', '0011_user_editor_role'),
    ]

    operations = [
    ]
