# Generated by Django 6.1 on 2026-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_specialistprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisttestquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='specialisttestquestion',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('TEXT', 'Text answer')], default='MULTIPLE_CHOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
