# Generated by Django 6.1 on 2026-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_specialisttestquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisttest',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
