# Generated by Django 6.1 on 2026-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_specialisttest_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('TEXT', 'Text answer'), ('CODE', 'Code answer')], default='MULTIPLE_CHOICE', max_length=20),
        ),
    ]
