# Generated by Django 6.1 on 2026-09-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_specialisttestquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisttestquestion',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('TEXT', 'Text answer'), ('CODE', 'Code answer'), ('TEXT_OR_CODE', 'Text or code')], default='MULTIPLE_CHOICE', max_length=20),
        ),
    ]
