# Generated by Django 5.2.5 on 2026-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_status_aa5436_idx',
            old_name='blog_blogpo_status_6e95d4_idx',
        ),
    ]
