# Generated by Django 5.1.15 on 2026-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card (immediate)'), ('BALANCE', 'Account balance'), ('CASH', 'Cash (pay on delivery)'), ('INVOICE', 'Invoice')], default='CARD', max_length=20),
        ),
    ]
