# Generated by Django 5.2.5 on 2026-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Visa Card'), ('BALANCE', 'Account balance')], default='CARD', max_length=20),
        ),
    ]
