# Generated by Django 5.2.5 on 2026-08-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card (Visa/Mastercard)'), ('BALANCE', 'Account balance')], default='CARD', max_length=20),
        ),
    ]
