# Generated by Django 5.2.5 on 2026-08-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='20% commission kept by the platform', max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='specialist_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='80% paid out to the specialist', max_digits=9),
        ),
    ]
