# Generated by Django 5.2.5 on 2026-08-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_platform_fee_order_specialist_earnings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card (Paystack)'), ('BALANCE', 'Account balance')], default='CARD', max_length=20),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What you're offering (e.g., 'Data Analysis Report')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of your offer')),
                ('price', models.DecimalField(decimal_places=2, help_text='Your quoted price in USD', max_digits=9)),
                ('delivery_days', models.PositiveIntegerField(default=5, help_text='Days to complete the work')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the offer expires (optional)', null=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, help_text='Auto-populated when offer is accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_offer', to='orders.order')),
                ('specialist', models.ForeignKey(limit_choices_to={'role': 'SPECIALIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('specialist', 'client', 'title')},
            },
        ),
    ]
