# Generated by Django 5.2.5 on 2026-08-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method_offer'),
        ('services', '0003_alter_category_id_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The service being ordered. Can be null for offers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service'),
        ),
    ]
