# Generated by Django 5.2.5 on 2026-08-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
