# Generated by Django 5.2.5 on 2026-08-19 11:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_offer_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Applied fee rate (e.g. 0.20 standard or 0.10 referral)', max_digits=4),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='5% referral reward credited to referrer', max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_bonus_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='Referrer who invited the client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission kept by the platform', max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='specialist_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Earnings paid out to the specialist', max_digits=9),
        ),
    ]
