# Generated by Django 5.2.5 on 2026-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_platform_fee_rate_order_referral_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card (Paystack)'), ('MPESA', 'M-Pesa'), ('BALANCE', 'Account balance')], default='CARD', max_length=20),
        ),
    ]
