# Generated by Django 5.2.5 on 2026-08-20 12:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revision_note',
            field=models.TextField(blank=True, help_text="Client's revision instructions"),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission kept by the platform (before referral payout)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Always 20% — platform commission', max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='5% of order price credited silently to referrer from platform share', max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending acceptance'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('DELIVERED', 'Delivered'), ('UNDER_REVISION', 'Under revision'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
