# Generated by Django 5.2.5 on 2026-08-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_revision_note_alter_order_platform_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.TextField(blank=True, help_text="Specialist's delivery note"),
        ),
    ]
