# Generated by Django 5.2.5 on 2026-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delivery_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card (Paystack)'), ('BALANCE', 'Account balance')], default='CARD', max_length=20),
        ),
    ]
