# Generated by Django 6.1 on 2026-09-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_is_simulated'),
        ('orders', '0016_alter_order_payment_method'),
    ]

    operations = [
    ]
