# Generated by Django 6.1 on 2026-09-15 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_editor_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='5% of the discounted first order credited to the referrer', max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('DELIVERED', 'Delivered'), ('UNDER_REVISION', 'Under revision'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
