# Generated by Django 5.2.5 on 2026-08-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('ORDER_NEW', 'New order placed'), ('ORDER_STATUS', 'Order status changed'), ('OFFER_RECEIVED', 'New offer received'), ('OFFER_ACCEPTED', 'Offer accepted'), ('OFFER_DECLINED', 'Offer declined'), ('REVIEW_RECEIVED', 'New review received'), ('DEPOSIT_DONE', 'Deposit completed'), ('REFERRAL_BONUS', 'Referral bonus credited')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, help_text='Deep-link URL for this notification', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
